/*
 * GENERATED by scripts/generate_font_metrics.py from the firmware's
 * lib/u8g2/u8g2_fonts.c at the pinned commit. Do not edit by hand;
 * regenerate, and expect the digests below to change only when the
 * firmware's fonts do.
 */
#include "remote_font_metrics.h"

/* u8g2_font_helvB08_tr, 1061 bytes, sha256 prefix ed8aaee9f846ad3e. */
static const unsigned char advances_helvB08_tr[REMOTE_FONT_GLYPH_COUNT] = {
    3, 4, 5, 6, 6, 8, 8, 3, 4, 4, 4, 6, 3, 5, 3, 4,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 5, 6, 5, 6,
    11, 8, 7, 8, 7, 6, 6, 8, 7, 3, 6, 7, 6, 10, 8, 8,
    7, 8, 7, 7, 7, 7, 8, 11, 8, 9, 7, 4, 4, 4, 5, 6,
    3, 6, 6, 5, 6, 6, 4, 6, 6, 3, 3, 6, 3, 9, 6, 6,
    6, 6, 4, 6, 4, 6, 6, 8, 7, 6, 6, 5, 3, 5, 6,
};

/* u8g2_font_haxrcorp4089_tr, 945 bytes, sha256 prefix 9d5ddc185cc43d0a. */
static const unsigned char advances_haxrcorp4089_tr[REMOTE_FONT_GLYPH_COUNT] = {
    2, 2, 4, 6, 6, 8, 7, 2, 4, 4, 6, 6, 3, 6, 2, 8,
    6, 3, 6, 6, 6, 6, 6, 6, 6, 6, 2, 3, 4, 6, 4, 6,
    9, 6, 6, 6, 6, 6, 6, 6, 6, 2, 6, 6, 6, 8, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 6, 4, 8, 4, 6, 6,
    4, 5, 5, 5, 5, 5, 3, 5, 5, 2, 3, 5, 2, 8, 5, 5,
    5, 5, 4, 4, 4, 5, 5, 8, 5, 5, 5, 4, 2, 4, 7,
};

const unsigned char* remote_font_advance_table(RemoteLayoutFont font) {
    switch(font) {
    case RemoteLayoutFontPrimary:
        return advances_helvB08_tr;
    case RemoteLayoutFontSecondary:
        return advances_haxrcorp4089_tr;
    }
    return advances_helvB08_tr;
}
