/*
 * Published NDEF reference vectors for FE6. Generated by
 * scripts/generate_ndef_vectors.py; do not edit by hand.
 *
 * Ground truth is ndeflib (the `ndef` package from the nfcpy project,
 * version 0.3.3), an independent NDEF implementation that shares no code with
 * this repository's remote_display/remote_ndef.c. The URI vectors are
 * compared byte for byte; the Wi-Fi credential is compared as a set of
 * attribute TLVs, since attribute order within a credential is not
 * significant and the two implementations order it differently.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char* name;
    const char* address;
    size_t length;
    uint8_t bytes[80];
} NdefUriVector;

static const NdefUriVector ndef_uri_vectors[] = {
    /* gallery_lower: http://192.168.72.1/ */
    {
        "gallery_lower",
        "http://192.168.72.1/",
        18,
        {0xD1, 0x01, 0x0E, 0x55, 0x03, 0x31, 0x39, 0x32, 0x2E, 0x31, 0x36, 0x38, 0x2E, 0x37, 0x32, 0x2E, 0x31, 0x2F},
    },
    /* https_short: https://a/b */
    {
        "https_short",
        "https://a/b",
        8,
        {0xD1, 0x01, 0x04, 0x55, 0x04, 0x61, 0x2F, 0x62},
    },
    /* no_scheme: x:y */
    {
        "no_scheme",
        "x:y",
        8,
        {0xD1, 0x01, 0x04, 0x55, 0x00, 0x78, 0x3A, 0x79},
    },
    /* http_host: http://stopbath.local/ */
    {
        "http_host",
        "http://stopbath.local/",
        20,
        {0xD1, 0x01, 0x10, 0x55, 0x03, 0x73, 0x74, 0x6F, 0x70, 0x62, 0x61, 0x74, 0x68, 0x2E, 0x6C, 0x6F, 0x63, 0x61, 0x6C, 0x2F},
    },
};

static const int ndef_uri_vector_count =
    (int)(sizeof(ndef_uri_vectors) / sizeof(ndef_uri_vectors[0]));

/* The Wi-Fi payload remote_ndef is given, and the ndeflib WSC record it is
 * checked against as an attribute set. */
static const char* const ndef_wsc_payload = "WIFI:T:WPA;S:StopBathExample;P:example1;;";
static const uint8_t ndef_wsc_reference[] = {0xD2, 0x17, 0x29, 0x61, 0x70, 0x70, 0x6C, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x2F, 0x76, 0x6E, 0x64, 0x2E, 0x77, 0x66, 0x61, 0x2E, 0x77, 0x73, 0x63, 0x10, 0x0E, 0x00, 0x25, 0x10, 0x03, 0x00, 0x02, 0x00, 0x20, 0x10, 0x27, 0x00, 0x08, 0x65, 0x78, 0x61, 0x6D, 0x70, 0x6C, 0x65, 0x31, 0x10, 0x45, 0x00, 0x0F, 0x53, 0x74, 0x6F, 0x70, 0x42, 0x61, 0x74, 0x68, 0x45, 0x78, 0x61, 0x6D, 0x70, 0x6C, 0x65};
static const size_t ndef_wsc_reference_length = sizeof(ndef_wsc_reference);

