/*
 * Published QR test vectors for FE5 ("known payload produces a known matrix,
 * against published test vectors"). Generated by scripts/generate_qr_vectors.sh;
 * do not edit by hand.
 *
 * Ground truth is an INDEPENDENT encoder, libqrencode (Kentaro Fukuchi,
 * qrencode version 4.1.1, packaged as qrencode on Debian and Ubuntu), which shares no code
 * with the nayuki qrcodegen this project vendors. Each matrix below was emitted
 * by the product path remote_qr_encode() AND reproduced module for module by
 * libqrencode at the version, error correction level, and mode named on the
 * vector, so the test that consumes this header is a cross check between two
 * unrelated implementations, not a snapshot of one. '1' is a dark module, '0'
 * light; the top left module is the finder corner and is always dark.
 *
 * remote_qr_encode() uses boostEcl, so a short payload is carried at a higher
 * error correction level than the L it starts from when the same version has
 * room; the level shown is the one both encoders agreed on. Payloads whose two
 * encoders chose different data mask patterns (a valid free choice on a penalty
 * tie) are not used, since only an exact match is evidence.
 */
#pragma once

typedef struct {
    const char* name;
    const char* payload;
    int side;
    const char* rows[29];
} QrPublishedVector;

static const QrPublishedVector qr_published_vectors[] = {
    /* gallery_address_v1: v1, ECC M, mode auto; confirmed identical to libqrencode. */
    {
        "gallery_address_v1",
        "HTTP://192.168.72.1/",
        21,
        {
            "111111100011101111111",
            "100000100010101000001",
            "101110101111001011101",
            "101110101010001011101",
            "101110101000101011101",
            "100000101010101000001",
            "111111101010101111111",
            "000000001100100000000",
            "101111100000101111100",
            "101101010011011110001",
            "011010100010000010001",
            "001100011110110011110",
            "111111100110101000000",
            "000000001000110001111",
            "111111100001100111100",
            "100000101010110001001",
            "101110101000010101001",
            "101110101010101100000",
            "101110101010011111100",
            "100000100110101101001",
            "111111101111111011000",
        },
    },
    /* gallery_deep_url_v2: v2, ECC M, mode auto; confirmed identical to libqrencode. */
    {
        "gallery_deep_url_v2",
        "HTTP://192.168.72.1/G/2/PHOTOS/LATEST",
        25,
        {
            "1111111011111100001111111",
            "1000001011011000001000001",
            "1011101011101001001011101",
            "1011101001010011101011101",
            "1011101010101110001011101",
            "1000001000110100101000001",
            "1111111010101010101111111",
            "0000000001111010100000000",
            "1001111110100001110010111",
            "0101100100100000011111100",
            "1111111000110010010010001",
            "0001000010110011000101010",
            "1100011111111100010100010",
            "1001010001001101010010100",
            "1100001111001000111100100",
            "1001010110001100101101011",
            "1000011001101001111110111",
            "0000000011000011100011000",
            "1111111011001010101011110",
            "1000001010000110100010100",
            "1011101010101100111111101",
            "1011101010011100100000111",
            "1011101000110001011100011",
            "1000001000010110110110010",
            "1111111010110000111010111",
        },
    },
    /* wifi_credential_v3: v3, ECC M, mode 8bit; confirmed identical to libqrencode. */
    {
        "wifi_credential_v3",
        "WIFI:T:WPA;S:StopBathExample;P:example1;;",
        29,
        {
            "11111110011111001101101111111",
            "10000010000110110010101000001",
            "10111010111110010010101011101",
            "10111010100101111100001011101",
            "10111010111010001010101011101",
            "10000010111000111010001000001",
            "11111110101010101010101111111",
            "00000000101010111000000000000",
            "10111110001111000101001111100",
            "01100100101100101111101010110",
            "10100011101010011000011101000",
            "00001101100100110000111010011",
            "11111110111001010100100111100",
            "01100001011011101001100110110",
            "01000011001111010010110100100",
            "00101000000000110010001001000",
            "11100010000001001100000101011",
            "10011100001111101111101011010",
            "10011110110101011000000110000",
            "10110100100100111011010010001",
            "10110111000100010100111111100",
            "00000000110111001010100010100",
            "11111110011001110000101010100",
            "10000010101111000001100011000",
            "10111010101000101110111111011",
            "10111010101111000100000011011",
            "10111010111000010110011111110",
            "10000010011000110001101011010",
            "11111110101010111001001011000",
        },
    },
    /* byte_phrase_v2: v2, ECC L, mode auto; confirmed identical to libqrencode. */
    {
        "byte_phrase_v2",
        "stopbath guest gallery link",
        25,
        {
            "1111111010011010001111111",
            "1000001001100100101000001",
            "1011101000101101101011101",
            "1011101000001100101011101",
            "1011101001010110101011101",
            "1000001000101010001000001",
            "1111111010101010101111111",
            "0000000010110111100000000",
            "1101101001111011101000001",
            "0100000101001011000111000",
            "0111001010110001001010101",
            "0000100001101010100001111",
            "1101111101001001101100001",
            "1100010110010101010110010",
            "1110001010101001111101111",
            "1001010111110010011001110",
            "1011111000001101111111111",
            "0000000010000111100010100",
            "1111111001010110101011001",
            "1000001001001101100011010",
            "1011101011011001111111000",
            "1011101010010011011000111",
            "1011101001111011010110011",
            "1000001011110001001001111",
            "1111111011001000101010001",
        },
    },
};

static const int qr_published_vector_count =
    (int)(sizeof(qr_published_vectors) / sizeof(qr_published_vectors[0]));
