/*
 * FE6, the reference-vector criteria for the NFC surface. The record builders
 * were written and unit tested at the FD15 to FD17 experiment against the
 * firmware's parser and Android's; this file adds the FE6 cross check against an
 * INDEPENDENT implementation, ndeflib (the `ndef` package from nfcpy), which
 * shares no code with remote_display/remote_ndef.c. The vectors are in
 * ndef_published_vectors.h, generated by scripts/generate_ndef_vectors.py.
 *
 * FE6 sets two bars, and this meets both:
 *  - the URI record against published NDEF test vectors: byte for byte.
 *  - the Wi-Fi credential against a known good reference: same header, type,
 *    credential wrapper, and set of attribute TLVs (order within a credential is
 *    not significant and the two implementations order it differently).
 *
 * It also proves the two FE6 properties that are structural rather than about a
 * single record: the QR and the NFC record for one page are derived from one
 * value and cannot present different networks, and no payload is retained in a
 * builder's buffer once a later build refuses.
 */
#include "test_support.h"

#include "../remote_display/remote_ndef.h"
#include "../remote_display/remote_qr.h"
#include "ndef_published_vectors.h"

/* Finds the first occurrence of a byte run within another, or -1. */
static int find_bytes(const uint8_t* haystack, size_t haystack_length, const uint8_t* needle, size_t needle_length) {
    if(needle_length == 0 || needle_length > haystack_length) return -1;
    for(size_t start = 0; start + needle_length <= haystack_length; start++) {
        if(memcmp(haystack + start, needle, needle_length) == 0) return (int)start;
    }
    return -1;
}

/* Locates the credential (attribute 0x100E) body inside a WSC record: the bytes
 * of the credential's own attribute TLVs. Returns false if the record is not the
 * expected single short media-type record wrapping one credential. */
static bool wsc_credential_body(const RemoteNdefMessage* message, const uint8_t** body, size_t* body_length) {
    if(message->length < 4) return false;
    size_t type_length = message->bytes[1];
    size_t payload_offset = 3 + type_length;
    if(payload_offset + 4 > message->length) return false;
    /* Attribute id 0x100E, then a big-endian 16 bit length. */
    if(message->bytes[payload_offset] != 0x10 || message->bytes[payload_offset + 1] != 0x0E) return false;
    size_t credential_length = ((size_t)message->bytes[payload_offset + 2] << 8) | message->bytes[payload_offset + 3];
    size_t credential_offset = payload_offset + 4;
    if(credential_offset + credential_length > message->length) return false;
    *body = message->bytes + credential_offset;
    *body_length = credential_length;
    return true;
}

static void the_uri_records_match_the_published_vectors(RemoteTestReport* report) {
    for(int vector_index = 0; vector_index < ndef_uri_vector_count; vector_index++) {
        const NdefUriVector* vector = &ndef_uri_vectors[vector_index];
        RemoteNdefMessage message;
        REMOTE_TEST_ASSERT(report, remote_ndef_build_uri_message(vector->address, &message), vector->name);
        REMOTE_TEST_ASSERT_EQUAL_INT(report, (int)vector->length, (int)message.length, vector->name);
        REMOTE_TEST_ASSERT(report, message.length == vector->length && memcmp(message.bytes, vector->bytes, vector->length) == 0, vector->name);
    }
}

static void the_wifi_credential_matches_the_reference_attribute_set(RemoteTestReport* report) {
    RemoteNdefMessage ours;
    REMOTE_TEST_ASSERT(report, remote_ndef_build_wifi_message(ndef_wsc_payload, &ours), "our record builds");

    /* Everything up to and including the credential header is byte identical to
     * the reference: header, type length, payload length, the media type, and
     * the credential attribute and its length. Only the attribute order inside
     * differs. */
    REMOTE_TEST_ASSERT(report, ours.length == ndef_wsc_reference_length, "same total length");
    size_t prefix = 30; /* D2, type len, payload len, 23 byte type, 10 0E len16 */
    REMOTE_TEST_ASSERT(report, ours.length >= prefix && memcmp(ours.bytes, ndef_wsc_reference, prefix) == 0, "header, type, and credential wrapper identical");

    /* The credential bodies carry the same set of attribute TLVs. Each TLV is
     * self delimiting and unique, so every reference attribute appearing in our
     * body, at equal body length, proves set equality regardless of order. */
    const uint8_t* our_body = NULL;
    size_t our_body_length = 0;
    RemoteNdefMessage reference_message;
    memset(&reference_message, 0, sizeof(reference_message));
    memcpy(reference_message.bytes, ndef_wsc_reference, ndef_wsc_reference_length);
    reference_message.length = ndef_wsc_reference_length;
    const uint8_t* reference_body = NULL;
    size_t reference_body_length = 0;
    REMOTE_TEST_ASSERT(report, wsc_credential_body(&ours, &our_body, &our_body_length), "our credential parses");
    REMOTE_TEST_ASSERT(report, wsc_credential_body(&reference_message, &reference_body, &reference_body_length), "reference credential parses");
    REMOTE_TEST_ASSERT(report, our_body_length == reference_body_length, "same credential body length, so no extra attributes");

    int attributes_checked = 0;
    size_t position = 0;
    while(position + 4 <= reference_body_length) {
        size_t attribute_length = ((size_t)reference_body[position + 2] << 8) | reference_body[position + 3];
        size_t tlv_length = 4 + attribute_length;
        if(position + tlv_length > reference_body_length) break;
        int found = find_bytes(our_body, our_body_length, reference_body + position, tlv_length);
        REMOTE_TEST_ASSERT(report, found >= 0, "each reference attribute is present in our credential");
        attributes_checked++;
        position += tlv_length;
    }
    REMOTE_TEST_ASSERT_EQUAL_INT(report, 3, attributes_checked, "the three attributes (SSID, auth type, network key)");
}

static void one_value_drives_both_surfaces_and_they_cannot_diverge(RemoteTestReport* report) {
    /* The record and the QR are built from the same payload string; there is no
     * second source of the value. The security consequence is what matters: the
     * network the NFC provisions (SSID and key) is exactly the one named in the
     * value the QR encodes. Proven by extracting the SSID and key from the built
     * record and matching them against the payload's own fields. */
    static const char payload[] = "WIFI:T:WPA;S:StopBathExample;P:example1;;";
    static const char expected_ssid[] = "StopBathExample";
    static const char expected_key[] = "example1";

    RemoteQrMatrix matrix;
    REMOTE_TEST_ASSERT(report, remote_qr_encode(payload, &matrix), "the QR encodes the value");

    RemoteNdefMessage message;
    REMOTE_TEST_ASSERT(report, remote_ndef_build_wifi_message(payload, &message), "the NFC record builds from the same value");

    /* SSID attribute 0x1045 and network key 0x1027 carry the payload's S and P
     * fields verbatim, so the two surfaces cannot name different networks. */
    uint8_t ssid_tlv[4 + sizeof(expected_ssid) - 1];
    ssid_tlv[0] = 0x10;
    ssid_tlv[1] = 0x45;
    ssid_tlv[2] = 0x00;
    ssid_tlv[3] = (uint8_t)(sizeof(expected_ssid) - 1);
    memcpy(ssid_tlv + 4, expected_ssid, sizeof(expected_ssid) - 1);
    REMOTE_TEST_ASSERT(report, find_bytes(message.bytes, message.length, ssid_tlv, sizeof(ssid_tlv)) >= 0, "the record's SSID is the payload's SSID");

    uint8_t key_tlv[4 + sizeof(expected_key) - 1];
    key_tlv[0] = 0x10;
    key_tlv[1] = 0x27;
    key_tlv[2] = 0x00;
    key_tlv[3] = (uint8_t)(sizeof(expected_key) - 1);
    memcpy(key_tlv + 4, expected_key, sizeof(expected_key) - 1);
    REMOTE_TEST_ASSERT(report, find_bytes(message.bytes, message.length, key_tlv, sizeof(key_tlv)) >= 0, "the record's key is the payload's passphrase");
}

static void a_refused_build_retains_no_earlier_payload(RemoteTestReport* report) {
    /* No payload survives once a build refuses: the buffer is cleared, so a
     * stale network can never be presented after a page whose payload does not
     * encode (FE6, "no payload is retained"). */
    RemoteNdefMessage message;
    REMOTE_TEST_ASSERT(report, remote_ndef_build_wifi_message("WIFI:T:WPA;S:StopBathExample;P:example1;;", &message), "a good payload builds");
    REMOTE_TEST_ASSERT(report, message.length > 0, "and fills the buffer");

    /* A refused payload (wrong security type) must leave nothing behind. */
    REMOTE_TEST_ASSERT(report, !remote_ndef_build_wifi_message("WIFI:T:WEP;S:StopBathExample;P:example1;;", &message), "the next payload is refused");
    REMOTE_TEST_ASSERT_EQUAL_INT(report, 0, (int)message.length, "the buffer is empty");
    bool any_nonzero = false;
    for(size_t byte_index = 0; byte_index < sizeof(message.bytes); byte_index++) {
        if(message.bytes[byte_index] != 0) any_nonzero = true;
    }
    REMOTE_TEST_ASSERT(report, !any_nonzero, "no byte of the earlier record remains");

    /* The same holds for the URI builder. */
    REMOTE_TEST_ASSERT(report, remote_ndef_build_uri_message("http://192.168.72.1/", &message), "a good address builds");
    REMOTE_TEST_ASSERT(report, !remote_ndef_build_uri_message("", &message), "an empty address is refused");
    REMOTE_TEST_ASSERT_EQUAL_INT(report, 0, (int)message.length, "the buffer is empty after the refusal");
}

int main(void) {
    static const RemoteTestCase test_cases[] = {
        {"the uri records match the published vectors", the_uri_records_match_the_published_vectors},
        {"the wifi credential matches the reference attribute set", the_wifi_credential_matches_the_reference_attribute_set},
        {"one value drives both surfaces and they cannot diverge", one_value_drives_both_surfaces_and_they_cannot_diverge},
        {"a refused build retains no earlier payload", a_refused_build_retains_no_earlier_payload},
    };
    return remote_test_run_all(test_cases, REMOTE_TEST_ROW_COUNT(test_cases));
}
