/*
 * GENERATED by scripts/generate_protocol_tables.py from protocol.json.
 * Do not edit by hand; edit protocol.json, regenerate, and record the
 * change in PROTOCOL.md. A test fails if this file and the table differ.
 */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define REMOTE_PROTOCOL_VERSION 1
#define REMOTE_PROTOCOL_TERMINATOR '\n'
#define REMOTE_PROTOCOL_FIELD_SEPARATOR ' '
#define REMOTE_PROTOCOL_NAME_VALUE_SEPARATOR '='
#define REMOTE_PROTOCOL_ESCAPE '%'
#define REMOTE_PROTOCOL_UNRESERVED "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"

#define REMOTE_PROTOCOL_MAXIMUM_MESSAGE_LENGTH 512
#define REMOTE_PROTOCOL_MAXIMUM_PAYLOAD_LENGTH 256
#define REMOTE_PROTOCOL_MAXIMUM_PERIPHERAL_TOKEN_LENGTH 32
#define REMOTE_PROTOCOL_MAXIMUM_DELIVERED_COUNT 9999
#define REMOTE_PROTOCOL_MAXIMUM_PROTOCOL_VERSION 65535
#define REMOTE_PROTOCOL_MAXIMUM_INBOUND_MESSAGES_PER_SECOND 10
#define REMOTE_PROTOCOL_MAXIMUM_INBOUND_BURST 20
#define REMOTE_PROTOCOL_CONSECUTIVE_MALFORMED_BEFORE_LINK_DROP 5
#define REMOTE_PROTOCOL_PERIPHERAL_OUTBOUND_QUEUE_DEPTH 4

/* Derived from the table: the widest verb and the longest text value. */
#define REMOTE_PROTOCOL_MAX_FIELDS_PER_VERB 5
#define REMOTE_PROTOCOL_MAX_TEXT_LENGTH 256

typedef enum {
    RemoteProtocolEventCenterShort,
    RemoteProtocolEventCenterLong,
    RemoteProtocolEventLeftShort,
    RemoteProtocolEventRightShort,
    RemoteProtocolEventBackShort,
    RemoteProtocolEventCount,
} RemoteProtocolEvent;

typedef enum {
    RemoteProtocolStatusReady,
    RemoteProtocolStatusPresenting,
    RemoteProtocolStatusGuestConnected,
    RemoteProtocolStatusTerminating,
    RemoteProtocolStatusRecoveryRequired,
    RemoteProtocolStatusCount,
} RemoteProtocolStatus;

typedef enum {
    RemoteProtocolPageNone,
    RemoteProtocolPageWifi,
    RemoteProtocolPageGuest,
    RemoteProtocolPageCount,
} RemoteProtocolPage;

typedef enum {
    RemoteProtocolErrorNone,
    RemoteProtocolErrorBadVersion,
    RemoteProtocolErrorNoHello,
    RemoteProtocolErrorMalformed,
    RemoteProtocolErrorBadVerb,
    RemoteProtocolErrorBadField,
    RemoteProtocolErrorNoField,
    RemoteProtocolErrorBadValue,
    RemoteProtocolErrorTooLong,
    RemoteProtocolErrorRateLimit,
    RemoteProtocolErrorGuard,
    RemoteProtocolErrorActive,
    RemoteProtocolErrorNoSession,
    RemoteProtocolErrorBadState,
    RemoteProtocolErrorNotAllowed,
    RemoteProtocolErrorStartFail,
    RemoteProtocolErrorEndFail,
    RemoteProtocolErrorCount,
} RemoteProtocolError;

typedef enum {
    RemoteProtocolEnumerationEvent,
    RemoteProtocolEnumerationStatus,
    RemoteProtocolEnumerationPage,
    RemoteProtocolEnumerationError,
    RemoteProtocolEnumerationCount,
} RemoteProtocolEnumeration;

typedef enum {
    RemoteProtocolVerbHello,
    RemoteProtocolVerbButton,
    RemoteProtocolVerbState,
    RemoteProtocolVerbDisplay,
    RemoteProtocolVerbCount,
} RemoteProtocolVerb;

enum {
    RemoteProtocolHelloFieldVersion = 0,
    RemoteProtocolHelloFieldPeripheral = 1,
    RemoteProtocolHelloFieldLocked = 2,
    RemoteProtocolHelloFieldCount = 3,
};

enum {
    RemoteProtocolButtonFieldEvent = 0,
    RemoteProtocolButtonFieldForegrounded = 1,
    RemoteProtocolButtonFieldUnlocked = 2,
    RemoteProtocolButtonFieldCount = 3,
};

enum {
    RemoteProtocolStateFieldLocked = 0,
    RemoteProtocolStateFieldCount = 1,
};

enum {
    RemoteProtocolDisplayFieldStatus = 0,
    RemoteProtocolDisplayFieldPage = 1,
    RemoteProtocolDisplayFieldPayload = 2,
    RemoteProtocolDisplayFieldDelivered = 3,
    RemoteProtocolDisplayFieldError = 4,
    RemoteProtocolDisplayFieldCount = 5,
};

typedef enum {
    RemoteProtocolDirectionPeripheralToAppliance,
    RemoteProtocolDirectionApplianceToPeripheral,
} RemoteProtocolDirection;

typedef enum {
    RemoteProtocolFieldTypeInteger,
    RemoteProtocolFieldTypeBoolean,
    RemoteProtocolFieldTypeEnumeration,
    RemoteProtocolFieldTypeToken,
    RemoteProtocolFieldTypeText,
} RemoteProtocolFieldType;

typedef struct {
    const char* name;
    RemoteProtocolFieldType type;
    /* Valid when type is enumeration. */
    RemoteProtocolEnumeration enumeration;
    /* Valid when type is integer. */
    uint32_t minimum;
    uint32_t maximum;
    /* Valid when type is token or text. */
    size_t maximum_length;
} RemoteProtocolFieldDescriptor;

typedef struct {
    const char* name;
    RemoteProtocolDirection direction;
    const RemoteProtocolFieldDescriptor* fields;
    int field_count;
} RemoteProtocolVerbDescriptor;

const RemoteProtocolVerbDescriptor* remote_protocol_verb_descriptor(RemoteProtocolVerb verb);

/* The wire spellings of an enumeration, in index order. */
const char* const* remote_protocol_enumeration_values(RemoteProtocolEnumeration enumeration, int* value_count);

#ifdef __cplusplus
}
#endif
