/*
 * GENERATED by scripts/generate_protocol_tables.py from protocol.json.
 * Do not edit by hand; edit protocol.json, regenerate, and record the
 * change in PROTOCOL.md. A test fails if this file and the table differ.
 */
#include "remote_protocol_tables.h"

static const char* const event_values[] = {
    "CENTER_SHORT",
    "CENTER_LONG",
    "LEFT_SHORT",
    "RIGHT_SHORT",
    "BACK_SHORT",
};

static const char* const status_values[] = {
    "READY",
    "PRESENTING",
    "GUEST_CONNECTED",
    "TERMINATING",
    "RECOVERY_REQUIRED",
};

static const char* const page_values[] = {
    "NONE",
    "WIFI",
    "GUEST",
};

static const char* const error_values[] = {
    "NONE",
    "BAD_VERSION",
    "NO_HELLO",
    "MALFORMED",
    "BAD_VERB",
    "BAD_FIELD",
    "NO_FIELD",
    "BAD_VALUE",
    "TOO_LONG",
    "RATE_LIMIT",
    "GUARD",
    "ACTIVE",
    "NO_SESSION",
    "BAD_STATE",
    "NOT_ALLOWED",
    "START_FAIL",
    "END_FAIL",
};

static const RemoteProtocolFieldDescriptor hello_fields[] = {
    {"version", RemoteProtocolFieldTypeInteger, RemoteProtocolEnumerationCount, 1U, 65535U, 0U},
    {"peripheral", RemoteProtocolFieldTypeToken, RemoteProtocolEnumerationCount, 0U, 0U, 32U},
    {"locked", RemoteProtocolFieldTypeBoolean, RemoteProtocolEnumerationCount, 0U, 0U, 0U},
};

static const RemoteProtocolFieldDescriptor button_fields[] = {
    {"event", RemoteProtocolFieldTypeEnumeration, RemoteProtocolEnumerationEvent, 0U, 0U, 0U},
    {"foregrounded", RemoteProtocolFieldTypeBoolean, RemoteProtocolEnumerationCount, 0U, 0U, 0U},
    {"unlocked", RemoteProtocolFieldTypeBoolean, RemoteProtocolEnumerationCount, 0U, 0U, 0U},
};

static const RemoteProtocolFieldDescriptor state_fields[] = {
    {"locked", RemoteProtocolFieldTypeBoolean, RemoteProtocolEnumerationCount, 0U, 0U, 0U},
};

static const RemoteProtocolFieldDescriptor display_fields[] = {
    {"status", RemoteProtocolFieldTypeEnumeration, RemoteProtocolEnumerationStatus, 0U, 0U, 0U},
    {"page", RemoteProtocolFieldTypeEnumeration, RemoteProtocolEnumerationPage, 0U, 0U, 0U},
    {"payload", RemoteProtocolFieldTypeText, RemoteProtocolEnumerationCount, 0U, 0U, 256U},
    {"delivered", RemoteProtocolFieldTypeInteger, RemoteProtocolEnumerationCount, 0U, 9999U, 0U},
    {"error", RemoteProtocolFieldTypeEnumeration, RemoteProtocolEnumerationError, 0U, 0U, 0U},
};

static const RemoteProtocolVerbDescriptor verb_descriptors[] = {
    {"HELLO", RemoteProtocolDirectionPeripheralToAppliance, hello_fields, 3},
    {"BUTTON", RemoteProtocolDirectionPeripheralToAppliance, button_fields, 3},
    {"STATE", RemoteProtocolDirectionPeripheralToAppliance, state_fields, 1},
    {"DISPLAY", RemoteProtocolDirectionApplianceToPeripheral, display_fields, 5},
};

const RemoteProtocolVerbDescriptor* remote_protocol_verb_descriptor(RemoteProtocolVerb verb) {
    /* Unsigned compare: a negative wraps high and is caught too, and it
     * warns nothing where the enum is unsigned (arm -fshort-enums). */
    if((unsigned int)verb >= (unsigned int)RemoteProtocolVerbCount) return NULL;
    return &verb_descriptors[verb];
}

const char* const* remote_protocol_enumeration_values(RemoteProtocolEnumeration enumeration, int* value_count) {
    switch(enumeration) {
    case RemoteProtocolEnumerationEvent:
        *value_count = 5;
        return event_values;
    case RemoteProtocolEnumerationStatus:
        *value_count = 5;
        return status_values;
    case RemoteProtocolEnumerationPage:
        *value_count = 3;
        return page_values;
    case RemoteProtocolEnumerationError:
        *value_count = 17;
        return error_values;
    case RemoteProtocolEnumerationCount:
        break;
    }
    *value_count = 0;
    return NULL;
}
