#!/usr/bin/env python3
"""
Generates remote_display/remote_font_metrics.c from the firmware's own u8g2
font data, so the host side layout truncates text by the same glyph advances
the device draws with (specification 0.2: measured, not guessed).

Usage:
    python3 scripts/generate_font_metrics.py PATH_TO_FIRMWARE/lib/u8g2/u8g2_fonts.c

The firmware checkout must be the pinned commit recorded in
docs/evaluation/ACTUAL_CONTRACT_EVALUATION.md. The generated file records the
font names and a digest of each font's bytes so a regeneration against a
different firmware is visible in the diff.

Fonts are the two the firmware maps to FontPrimary and FontSecondary in
applications/services/gui/canvas.c at the pinned commit.
"""

import hashlib
import re
import sys
from pathlib import Path

FONTS = (
    ("helvB08_tr", "RemoteLayoutFontPrimary"),
    ("haxrcorp4089_tr", "RemoteLayoutFontSecondary"),
)
FIRST_GLYPH = 0x20
LAST_GLYPH = 0x7E
HEADER_LENGTH = 23

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "remote_display" / "remote_font_metrics.c"


def c_string_bytes(literal_body: str) -> bytes:
    out = bytearray()
    index = 0
    length = len(literal_body)
    while index < length:
        character = literal_body[index]
        if character != "\\":
            out.append(ord(character))
            index += 1
            continue
        following = literal_body[index + 1]
        if following in "01234567":
            end = index + 1
            digits = ""
            while end < length and len(digits) < 3 and literal_body[end] in "01234567":
                digits += literal_body[end]
                end += 1
            out.append(int(digits, 8))
            index = end
            continue
        if following == "x":
            end = index + 2
            digits = ""
            while end < length and literal_body[end] in "0123456789abcdefABCDEF":
                digits += literal_body[end]
                end += 1
            out.append(int(digits, 16) & 0xFF)
            index = end
            continue
        escapes = {"n": 10, "t": 9, "r": 13, "\\": 92, '"': 34, "'": 39, "a": 7, "b": 8, "f": 12, "v": 11}
        out.append(escapes[following])
        index += 2
    return bytes(out)


def font_bytes(source: str, name: str) -> bytes:
    start = source.index("const uint8_t u8g2_font_%s[" % name)
    equals = source.index("=", start)
    # A literal ';' byte can appear inside the data, so the statement end is
    # found by walking adjacent string literals rather than searching for ';'.
    literal = re.compile(r'\s*"((?:[^"\\]|\\.)*)"')
    parts = []
    position = equals + 1
    while True:
        match = literal.match(source, position)
        if not match:
            break
        parts.append(match.group(1))
        position = match.end()
    return b"".join(c_string_bytes(part) for part in parts)


class BitReader:
    def __init__(self, data: bytes, position: int):
        self.data = data
        self.position = position
        self.bit = 0

    def read(self, bit_count: int) -> int:
        value = 0
        for bit_index in range(bit_count):
            value |= ((self.data[self.position] >> self.bit) & 1) << bit_index
            self.bit += 1
            if self.bit == 8:
                self.bit = 0
                self.position += 1
        return value

    def read_signed(self, bit_count: int) -> int:
        return self.read(bit_count) - (1 << (bit_count - 1))


def glyph_advances(data: bytes) -> dict:
    # u8g2 font header, as read by u8g2_font_setup in u8g2_font.c.
    bits_per_char_width = data[4]
    bits_per_char_height = data[5]
    bits_per_char_x = data[6]
    bits_per_char_y = data[7]
    bits_per_delta_x = data[8]
    advances = {}
    position = HEADER_LENGTH
    while position + 1 < len(data):
        encoding = data[position]
        glyph_length = data[position + 1]
        if glyph_length == 0:
            break
        reader = BitReader(data, position + 2)
        reader.read(bits_per_char_width)
        reader.read(bits_per_char_height)
        reader.read_signed(bits_per_char_x)
        reader.read_signed(bits_per_char_y)
        advances[encoding] = reader.read_signed(bits_per_delta_x)
        position += glyph_length
    return advances


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    source = Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace")

    lines = []
    lines.append("/*")
    lines.append(" * GENERATED by scripts/generate_font_metrics.py from the firmware's")
    lines.append(" * lib/u8g2/u8g2_fonts.c at the pinned commit. Do not edit by hand;")
    lines.append(" * regenerate, and expect the digests below to change only when the")
    lines.append(" * firmware's fonts do.")
    lines.append(" */")
    lines.append('#include "remote_font_metrics.h"')
    lines.append("")
    table_names = []
    for font_name, layout_font in FONTS:
        data = font_bytes(source, font_name)
        digest = hashlib.sha256(data).hexdigest()[:16]
        advances = glyph_advances(data)
        table_name = "advances_%s" % font_name
        table_names.append((layout_font, table_name))
        lines.append("/* u8g2_font_%s, %d bytes, sha256 prefix %s. */" % (font_name, len(data), digest))
        lines.append("static const unsigned char %s[REMOTE_FONT_GLYPH_COUNT] = {" % table_name)
        row = []
        for encoding in range(FIRST_GLYPH, LAST_GLYPH + 1):
            advance = advances.get(encoding, 0)
            if advance < 0 or advance > 255:
                raise SystemExit("advance out of range for glyph %d" % encoding)
            row.append("%d" % advance)
            if len(row) == 16:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        lines.append("};")
        lines.append("")
    lines.append("const unsigned char* remote_font_advance_table(RemoteLayoutFont font) {")
    lines.append("    switch(font) {")
    for layout_font, table_name in table_names:
        lines.append("    case %s:" % layout_font)
        lines.append("        return %s;" % table_name)
    lines.append("    }")
    lines.append("    return %s;" % table_names[0][1])
    lines.append("}")
    lines.append("")
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("wrote %s" % OUTPUT_PATH)
    return 0


if __name__ == "__main__":
    sys.exit(main())
