#!/usr/bin/env python3
"""
Generates protocol/remote_protocol_tables.h and protocol/remote_protocol_tables.c
from protocol.json, the single normative table (specification 0.7: the
grammar is expressed once and both the parser and the encoder are derived from
it; PROTOCOL.md explains the table).

Usage:
    python3 scripts/generate_protocol_tables.py            # write the files
    python3 scripts/generate_protocol_tables.py --check    # exit 1 if they differ

The --check form is what the test suite and continuous integration run, so a
hand edit to the generated files, or an edit to protocol.json without
regeneration, fails the build.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFINITION = ROOT / "protocol.json"
HEADER = ROOT / "protocol" / "remote_protocol_tables.h"
SOURCE = ROOT / "protocol" / "remote_protocol_tables.c"

FIELD_TYPES = ("integer", "boolean", "enumeration", "token", "text")


def pascal(identifier: str) -> str:
    return "".join(part.capitalize() for part in identifier.lower().replace("-", "_").split("_"))


def upper_macro(identifier: str) -> str:
    return identifier.upper().replace("-", "_")


def generate(definition: dict):
    version = definition["protocol_version"]
    bounds = definition["bounds"]
    enumerations = definition["enumerations"]
    verbs = definition["verbs"]
    framing = definition["framing"]

    max_fields = max(len(verb["fields"]) for verb in verbs)
    max_text = max(
        field.get("maximum_length", 0)
        for verb in verbs
        for field in verb["fields"]
        if field["type"] in ("token", "text")
    )
    banner = [
        "/*",
        " * GENERATED by scripts/generate_protocol_tables.py from protocol.json.",
        " * Do not edit by hand; edit protocol.json, regenerate, and record the",
        " * change in PROTOCOL.md. A test fails if this file and the table differ.",
        " */",
    ]

    header = list(banner)
    header += [
        "#pragma once",
        "",
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f"#define REMOTE_PROTOCOL_VERSION {version}",
        f"#define REMOTE_PROTOCOL_TERMINATOR '{framing['terminator'].encode('unicode_escape').decode()}'",
        f"#define REMOTE_PROTOCOL_FIELD_SEPARATOR '{framing['field_separator']}'",
        f"#define REMOTE_PROTOCOL_NAME_VALUE_SEPARATOR '{framing['name_value_separator']}'",
        f"#define REMOTE_PROTOCOL_ESCAPE '{framing['escape']}'",
        f'#define REMOTE_PROTOCOL_UNRESERVED "{framing["unreserved"]}"',
        "",
    ]
    for name, value in bounds.items():
        header.append(f"#define REMOTE_PROTOCOL_{upper_macro(name)} {value}")
    header += [
        "",
        "/* Derived from the table: the widest verb and the longest text value. */",
        f"#define REMOTE_PROTOCOL_MAX_FIELDS_PER_VERB {max_fields}",
        f"#define REMOTE_PROTOCOL_MAX_TEXT_LENGTH {max_text}",
        "",
    ]

    # Enumerations.
    for enumeration_name, values in enumerations.items():
        type_name = f"RemoteProtocol{pascal(enumeration_name)}"
        header.append("typedef enum {")
        for value in values:
            header.append(f"    {type_name}{pascal(value)},")
        header.append(f"    {type_name}Count,")
        header.append(f"}} {type_name};")
        header.append("")
    header.append("typedef enum {")
    for enumeration_name in enumerations:
        header.append(f"    RemoteProtocolEnumeration{pascal(enumeration_name)},")
    header.append("    RemoteProtocolEnumerationCount,")
    header.append("} RemoteProtocolEnumeration;")
    header.append("")

    # Verbs and per verb field indexes.
    header.append("typedef enum {")
    for verb in verbs:
        header.append(f"    RemoteProtocolVerb{pascal(verb['name'])},")
    header.append("    RemoteProtocolVerbCount,")
    header.append("} RemoteProtocolVerb;")
    header.append("")
    for verb in verbs:
        header.append("enum {")
        for index, field in enumerate(verb["fields"]):
            header.append(f"    RemoteProtocol{pascal(verb['name'])}Field{pascal(field['name'])} = {index},")
        header.append(f"    RemoteProtocol{pascal(verb['name'])}FieldCount = {len(verb['fields'])},")
        header.append("};")
        header.append("")

    header += [
        "typedef enum {",
        "    RemoteProtocolDirectionPeripheralToAppliance,",
        "    RemoteProtocolDirectionApplianceToPeripheral,",
        "} RemoteProtocolDirection;",
        "",
        "typedef enum {",
    ]
    for field_type in FIELD_TYPES:
        header.append(f"    RemoteProtocolFieldType{pascal(field_type)},")
    header += [
        "} RemoteProtocolFieldType;",
        "",
        "typedef struct {",
        "    const char* name;",
        "    RemoteProtocolFieldType type;",
        "    /* Valid when type is enumeration. */",
        "    RemoteProtocolEnumeration enumeration;",
        "    /* Valid when type is integer. */",
        "    uint32_t minimum;",
        "    uint32_t maximum;",
        "    /* Valid when type is token or text. */",
        "    size_t maximum_length;",
        "} RemoteProtocolFieldDescriptor;",
        "",
        "typedef struct {",
        "    const char* name;",
        "    RemoteProtocolDirection direction;",
        "    const RemoteProtocolFieldDescriptor* fields;",
        "    int field_count;",
        "} RemoteProtocolVerbDescriptor;",
        "",
        "const RemoteProtocolVerbDescriptor* remote_protocol_verb_descriptor(RemoteProtocolVerb verb);",
        "",
        "/* The wire spellings of an enumeration, in index order. */",
        "const char* const* remote_protocol_enumeration_values(RemoteProtocolEnumeration enumeration, int* value_count);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]

    source = list(banner)
    source += ['#include "remote_protocol_tables.h"', ""]
    for enumeration_name, values in enumerations.items():
        source.append(f"static const char* const {enumeration_name}_values[] = {{")
        for value in values:
            source.append(f'    "{value}",')
        source.append("};")
        source.append("")
    for verb in verbs:
        source.append(f"static const RemoteProtocolFieldDescriptor {verb['name'].lower()}_fields[] = {{")
        for field in verb["fields"]:
            field_type = field["type"]
            enumeration = field.get("enumeration")
            enumeration_member = (
                f"RemoteProtocolEnumeration{pascal(enumeration)}" if enumeration else "RemoteProtocolEnumerationCount"
            )
            minimum = field.get("minimum", 0)
            maximum = field.get("maximum", 0)
            maximum_length = field.get("maximum_length", 0)
            source.append(
                f'    {{"{field["name"]}", RemoteProtocolFieldType{pascal(field_type)}, {enumeration_member}, '
                f"{minimum}U, {maximum}U, {maximum_length}U}},"
            )
        source.append("};")
        source.append("")
    source.append("static const RemoteProtocolVerbDescriptor verb_descriptors[] = {")
    for verb in verbs:
        direction = (
            "RemoteProtocolDirectionPeripheralToAppliance"
            if verb["direction"] == "peripheral_to_appliance"
            else "RemoteProtocolDirectionApplianceToPeripheral"
        )
        source.append(
            f'    {{"{verb["name"]}", {direction}, {verb["name"].lower()}_fields, {len(verb["fields"])}}},'
        )
    source += [
        "};",
        "",
        "const RemoteProtocolVerbDescriptor* remote_protocol_verb_descriptor(RemoteProtocolVerb verb) {",
        "    /* Unsigned compare: a negative wraps high and is caught too, and it",
        "     * warns nothing where the enum is unsigned (arm -fshort-enums). */",
        "    if((unsigned int)verb >= (unsigned int)RemoteProtocolVerbCount) return NULL;",
        "    return &verb_descriptors[verb];",
        "}",
        "",
        "const char* const* remote_protocol_enumeration_values(RemoteProtocolEnumeration enumeration, int* value_count) {",
        "    switch(enumeration) {",
    ]
    for enumeration_name, values in enumerations.items():
        source.append(f"    case RemoteProtocolEnumeration{pascal(enumeration_name)}:")
        source.append(f"        *value_count = {len(values)};")
        source.append(f"        return {enumeration_name}_values;")
    source += [
        "    case RemoteProtocolEnumerationCount:",
        "        break;",
        "    }",
        "    *value_count = 0;",
        "    return NULL;",
        "}",
        "",
    ]
    return "\n".join(header), "\n".join(source)


def main() -> int:
    definition = json.loads(DEFINITION.read_text(encoding="utf-8"))
    header, source = generate(definition)
    check = "--check" in sys.argv[1:]
    if check:
        current_header = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        current_source = SOURCE.read_text(encoding="utf-8") if SOURCE.exists() else ""
        if current_header != header or current_source != source:
            print("protocol tables differ from protocol.json; run scripts/generate_protocol_tables.py")
            return 1
        print("protocol tables match protocol.json")
        return 0
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(header, encoding="utf-8", newline="\n")
    SOURCE.write_text(source, encoding="utf-8", newline="\n")
    print(f"wrote {HEADER} and {SOURCE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
