#!/usr/bin/env python3
"""
Generates tests/ndef_published_vectors.h: the FE6 NDEF reference vectors, each
produced by an INDEPENDENT implementation, ndeflib (the `ndef` package, the NDEF
library from the nfcpy project), which shares no code with this repository's hand
written record builder in remote_display/remote_ndef.c.

FE6 asks for two different bars, and this produces both:

- the URI record is checked "against published NDEF test vectors": ndeflib
  encodes the NFC Forum URI RTD record, and the test asserts remote_ndef builds
  the same bytes exactly, for addresses where the abbreviation rule agrees (the
  lowercase http and https schemes and a scheme ndeflib does not abbreviate).
- the Wi-Fi credential record is checked "against a known good reference":
  ndeflib encodes the Wi-Fi Simple Configuration credential, and the test asserts
  remote_ndef produces the same header, type, credential wrapper, and set of
  attribute TLVs. The order of attributes within the credential is not compared,
  because it is not significant to a reader and the two implementations choose
  differently (this builder follows the WSC attribute order, ndeflib does not).

Usage (a Python 3 with ndeflib available):
    python3 -m pip install --user ndeflib   # once; not needed at test time
    python3 scripts/generate_ndef_vectors.py

The result is committed, so continuous integration needs neither ndeflib nor this
script. The header is consumed by tests/test_remote_ndef_vectors.c.
"""

import sys
import os

try:
    import ndef
except ImportError:
    sys.exit(
        "ndeflib is not installed; run: python3 -m pip install --user ndeflib\n"
        "(the generated header is committed, so this is only needed to regenerate)"
    )

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "tests", "ndef_published_vectors.h")

# Addresses where remote_ndef's abbreviation rule and ndeflib agree exactly. The
# production gallery address is upper case for the QR's alphanumeric mode and this
# builder abbreviates the scheme case insensitively, which ndeflib does not, so
# the upper case form is a deliberate deviation checked in test_remote_ndef.c, not
# a published vector here.
URI_INPUTS = [
    ("gallery_lower", "http://192.168.72.1/"),
    ("https_short", "https://a/b"),
    ("no_scheme", "x:y"),
    ("http_host", "http://stopbath.local/"),
]

# The example Wi-Fi payload in StopBath's grammar (real credentials never appear
# in the repository). The SSID, key, and WPA2-Personal auth type are what a phone
# reads.
WSC_PAYLOAD = "WIFI:T:WPA;S:StopBathExample;P:example1;;"
WSC_SSID = b"StopBathExample"
WSC_KEY = b"example1"


def encode_uri(address):
    return b"".join(ndef.message_encoder([ndef.UriRecord(address)]))


def encode_wsc(ssid, key):
    record = ndef.wifi.WifiSimpleConfigRecord()
    credential = ndef.wifi.Credential()
    credential.set_attribute("ssid", ssid)
    credential.set_attribute("network-key", key)
    credential.set_attribute("authentication-type", "WPA2-Personal")
    record.set_attribute("credential", credential)
    return b"".join(ndef.message_encoder([record]))


def c_array(data):
    return ", ".join("0x%02X" % b for b in data)


def main():
    version = getattr(ndef, "__version__", "unknown")
    lines = []
    a = lines.append
    a("/*")
    a(" * Published NDEF reference vectors for FE6. Generated by")
    a(" * scripts/generate_ndef_vectors.py; do not edit by hand.")
    a(" *")
    a(" * Ground truth is ndeflib (the `ndef` package from the nfcpy project,")
    a(" * version %s), an independent NDEF implementation that shares no code with" % version)
    a(" * this repository's remote_display/remote_ndef.c. The URI vectors are")
    a(" * compared byte for byte; the Wi-Fi credential is compared as a set of")
    a(" * attribute TLVs, since attribute order within a credential is not")
    a(" * significant and the two implementations order it differently.")
    a(" */")
    a("#pragma once")
    a("")
    a("#include <stddef.h>")
    a("#include <stdint.h>")
    a("")
    a("typedef struct {")
    a("    const char* name;")
    a("    const char* address;")
    a("    size_t length;")
    a("    uint8_t bytes[80];")
    a("} NdefUriVector;")
    a("")
    a("static const NdefUriVector ndef_uri_vectors[] = {")
    for name, address in URI_INPUTS:
        data = encode_uri(address)
        if len(data) > 80:
            sys.exit("URI vector %s too long for the fixed array" % name)
        a("    /* %s: %s */" % (name, address))
        a("    {")
        a('        "%s",' % name)
        a('        "%s",' % address)
        a("        %d," % len(data))
        a("        {%s}," % c_array(data))
        a("    },")
    a("};")
    a("")
    a("static const int ndef_uri_vector_count =")
    a("    (int)(sizeof(ndef_uri_vectors) / sizeof(ndef_uri_vectors[0]));")
    a("")
    wsc = encode_wsc(WSC_SSID, WSC_KEY)
    a("/* The Wi-Fi payload remote_ndef is given, and the ndeflib WSC record it is")
    a(" * checked against as an attribute set. */")
    a('static const char* const ndef_wsc_payload = "%s";' % WSC_PAYLOAD)
    a("static const uint8_t ndef_wsc_reference[] = {%s};" % c_array(wsc))
    a("static const size_t ndef_wsc_reference_length = sizeof(ndef_wsc_reference);")
    a("")

    with open(OUT, "w", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print("wrote %s (%d URI vectors, WSC %d bytes, ndeflib %s)"
          % (OUT, len(URI_INPUTS), len(wsc), version))


if __name__ == "__main__":
    main()
