#!/usr/bin/env bash
#
# Generates tests/qr_published_vectors.h: the FE5 published QR vectors, each a
# matrix emitted by the product path remote_qr_encode() and cross checked, module
# for module, against an INDEPENDENT encoder (specification 0.2: measured, not
# guessed; FE5 Tests first: "known payload produces a known matrix, against
# published test vectors").
#
# The independent encoder is libqrencode (Kentaro Fukuchi), which shares no code
# with the nayuki qrcodegen this project vendors, so an exact match is evidence
# of correctness in both rather than a snapshot of one. A payload is emitted as a
# vector only when the two implementations agree on every module; where they pick
# different, equally valid, data mask patterns (the standard leaves the choice
# free on a penalty tie) the payload is dropped rather than pinned to one side.
#
# Usage (a Debian or Ubuntu environment, so WSL on the author's machine):
#     scripts/generate_qr_vectors.sh
#
# It fetches the qrencode package with apt when the binary is not already
# available, builds a small dumper against the in tree remote_qr.c, regenerates
# the header, and refuses to write if any payload fails to match. The result is
# committed, so continuous integration needs neither qrencode nor this script.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/tests/qr_published_vectors.h"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cd "$REPO"

# name|payload|version|ecc|mode, each already confirmed to match. The version,
# error correction level and mode are what BOTH encoders settled on; ecc is the
# level remote_qr_encode()'s boostEcl raised to where the version had room.
VECTORS=(
  "gallery_address_v1|HTTP://192.168.72.1/|1|M|auto"
  "gallery_deep_url_v2|HTTP://192.168.72.1/G/2/PHOTOS/LATEST|2|M|auto"
  "wifi_credential_v3|WIFI:T:WPA;S:StopBathExample;P:example1;;|3|M|8bit"
  "byte_phrase_v2|stopbath guest gallery link|2|L|auto"
)

# Locate or fetch libqrencode, without needing root for the global install.
QR="$(command -v qrencode || true)"
if [ -z "$QR" ]; then
  echo "qrencode not on PATH; fetching the package into a private prefix..." >&2
  PREFIX="$WORK/prefix"
  mkdir -p "$PREFIX"
  ( cd "$WORK" && apt-get download qrencode libqrencode4 >/dev/null 2>&1 )
  for deb in "$WORK"/qrencode_*.deb "$WORK"/libqrencode4_*.deb; do
    dpkg-deb -x "$deb" "$PREFIX"
  done
  QR="$PREFIX/usr/bin/qrencode"
  export LD_LIBRARY_PATH="$PREFIX/usr/lib/$(uname -m)-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
QR_VERSION="$("$QR" --version 2>&1 | head -1)"

# A dumper that prints the PRODUCTION matrix as ## (dark) and spaces (light).
cat > "$WORK/qr_dump_prod.c" <<'EOF'
#include <stdio.h>
#include "remote_qr.h"
int main(int argc, char** argv) {
    if(argc < 2) return 2;
    RemoteQrMatrix m;
    if(!remote_qr_encode(argv[1], &m)) return 1;
    for(int y = 0; y < m.side; y++) {
        for(int x = 0; x < m.side; x++) fputs(remote_qr_module_is_dark(&m, x, y) ? "##" : "  ", stdout);
        putchar('\n');
    }
    return 0;
}
EOF
cc -O2 -Iremote_display -Ilib/qrcodegen -o "$WORK/qr_dump_prod" \
    "$WORK/qr_dump_prod.c" remote_display/remote_qr.c lib/qrcodegen/qrcodegen.c

# ## and spaces to a row of '1' and '0', one character per module.
canon() { awk '{r="";for(i=1;i<=length($0);i+=2){c=substr($0,i,1);r=r (c==" "?"0":"1")}print r}' "$1"; }

emit_header() {
  cat <<EOF
/*
 * Published QR test vectors for FE5 ("known payload produces a known matrix,
 * against published test vectors"). Generated by scripts/generate_qr_vectors.sh;
 * do not edit by hand.
 *
 * Ground truth is an INDEPENDENT encoder, libqrencode (Kentaro Fukuchi,
 * $QR_VERSION, packaged as qrencode on Debian and Ubuntu), which shares no code
 * with the nayuki qrcodegen this project vendors. Each matrix below was emitted
 * by the product path remote_qr_encode() AND reproduced module for module by
 * libqrencode at the version, error correction level, and mode named on the
 * vector, so the test that consumes this header is a cross check between two
 * unrelated implementations, not a snapshot of one. '1' is a dark module, '0'
 * light; the top left module is the finder corner and is always dark.
 *
 * remote_qr_encode() uses boostEcl, so a short payload is carried at a higher
 * error correction level than the L it starts from when the same version has
 * room; the level shown is the one both encoders agreed on. Payloads whose two
 * encoders chose different data mask patterns (a valid free choice on a penalty
 * tie) are not used, since only an exact match is evidence.
 */
#pragma once

typedef struct {
    const char* name;
    const char* payload;
    int side;
    const char* rows[29];
} QrPublishedVector;

static const QrPublishedVector qr_published_vectors[] = {
EOF

  for spec in "${VECTORS[@]}"; do
    IFS='|' read -r name payload version ecc mode <<< "$spec"
    local eightbit=""
    [ "$mode" = "8bit" ] && eightbit="-8"
    "$WORK/qr_dump_prod" "$payload" > "$WORK/prod.txt"
    canon "$WORK/prod.txt" > "$WORK/prod_bits.txt"
    "$QR" -t ASCII -m 0 -v "$version" -l "$ecc" $eightbit -o - "$payload" > "$WORK/ref.txt" 2>/dev/null
    canon "$WORK/ref.txt" > "$WORK/ref_bits.txt"
    if ! diff -q "$WORK/prod_bits.txt" "$WORK/ref_bits.txt" >/dev/null; then
      echo "FATAL: $name: remote_qr_encode() and libqrencode disagree; not writing." >&2
      exit 1
    fi
    local side
    side=$(wc -l < "$WORK/prod_bits.txt")
    echo "    /* $name: v$version, ECC $ecc, mode $mode; confirmed identical to libqrencode. */"
    echo "    {"
    echo "        \"$name\","
    echo "        \"$payload\","
    echo "        $side,"
    echo "        {"
    while IFS= read -r row; do echo "            \"$row\","; done < "$WORK/prod_bits.txt"
    echo "        },"
    echo "    },"
  done

  cat <<'EOF'
};

static const int qr_published_vector_count =
    (int)(sizeof(qr_published_vectors) / sizeof(qr_published_vectors[0]));
EOF
}

emit_header > "$OUT"
echo "wrote $OUT (${#VECTORS[@]} vectors, confirmed against $QR_VERSION)"
